global:
  scrape_interval:     15s

altering:
  altertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
        #alert manager

rule_files:
  - rules.yml
    
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - prometheus:9090
  - job_name: project1
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
        - project1:8080